# Generated by Django 5.0.4 on 2024-05-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_appeal_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeAppeal',
        ),
    ]
