# Generated by Django 5.0.4 on 2024-05-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_number', models.IntegerField()),
                ('word_uz', models.CharField(max_length=255)),
                ('word_ru', models.CharField(max_length=255)),
                ('word_en', models.CharField(max_length=255)),
                ('word_tk', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
                'db_table': 'dictionary',
                'ordering': ['word_number'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('word_description_uz', models.TextField()),
                ('word_description_ru', models.TextField(null=True)),
                ('word_description_en', models.TextField(null=True)),
                ('word_description_tk', models.TextField(null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dictionary.dictionary')),
            ],
        ),
    ]
