# Generated by Django 5.0.4 on 2024-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_date', models.DateTimeField(auto_now_add=True)),
                ('announcement_title', models.CharField(max_length=255)),
                ('announcement_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_title', models.CharField(max_length=255)),
                ('news_description', models.CharField(max_length=255)),
                ('news_image', models.ImageField(upload_to='news/')),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_title', models.CharField(max_length=255)),
                ('news_description', models.TextField()),
                ('news_image', models.ImageField(upload_to='news/')),
            ],
        ),
    ]
