# Generated by Django 5.0.4 on 2024-05-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tmsiti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_image', models.ImageField(upload_to='leaders/')),
                ('leader_position', models.CharField(max_length=100)),
                ('leader_name', models.CharField(max_length=255)),
                ('leader_days', models.CharField(max_length=10)),
                ('leader_phone', models.CharField(max_length=13)),
                ('leader_email', models.CharField(max_length=255)),
                ('leader_bachelor', models.CharField(blank=True, max_length=255, null=True)),
                ('leader_master', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leaderships',
                'db_table': 'leadership',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='units/')),
                ('staff_position', models.CharField(max_length=255)),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_phone', models.CharField(max_length=13)),
                ('staff_email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Units',
                'db_table': 'units',
            },
        ),
    ]
