# Generated by Django 5.0.4 on 2024-05-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tmsiti', '0002_leadership_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=100)),
                ('standard_description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Standards',
                'db_table': 'standards',
            },
        ),
        migrations.CreateModel(
            name='StandardsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_file', models.FileField(upload_to='standards/')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tmsiti.standards')),
            ],
        ),
    ]
