# Generated by Django 5.0.4 on 2024-05-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tmsiti', '0003_standards_standardsinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('description', models.TextField()),
                ('leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tmsiti.leadership')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
            },
        ),
    ]
