# Generated by Django 5.0.4 on 2024-05-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tmsiti', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.IntegerField(max_length=10, unique=True)),
                ('building_mark', models.CharField(max_length=15, unique=True)),
                ('building_name', models.CharField(max_length=255)),
                ('building_document', models.FileField(upload_to='buildings/')),
            ],
            options={
                'verbose_name_plural': 'Building Regulations',
                'db_table': 'building_regulations',
            },
        ),
    ]
